apiVersion: v1
kind: Pod
metadata:
  name: {{ include "studyon.celery.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "studyon.celery.labels" . | nindent 4 }}
spec:
  {{- with .Values.imagePullSecrets }}
  imagePullSecrets:
    {{- toYaml . | nindent 8 }}
  {{- end }}
  containers:
    - name: {{ include "studyon.celery.fullname" . }}
      image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
      imagePullPolicy: {{ .Values.image.pullPolicy }}
      envFrom: 
        - configMapRef: 
          name: {{ include "studyon.fullname" . }}
        - secretRef:
          name: {{ include "studyon.fullname" . }}
        - secretRef:
          name: {{ include "studyon.db.fullname" . }}
      ports:
        - name: http
          containerPort: {{ .Values.django.containerPort }}
          protocol: TCP
      command: ["celery", "-A", "config", "worker", "-l", "info"]
---
apiVersion: v1
kind: Pod
metadata:
  name: {{ include "studyon.beat.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "studyon.celery.labels" . | nindent 4 }}
spec:
  {{- with .Values.imagePullSecrets }}
  imagePullSecrets:
    {{- toYaml . | nindent 8 }}
  {{- end }}
  containers:
    - name: {{ include "studyon.beat.fullname" . }}
      image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
      imagePullPolicy: {{ .Values.image.pullPolicy }}
      envFrom: 
        - configMapRef: 
          name: {{ include "studyon.fullname" . }}
        - secretRef:
          name: {{ include "studyon.fullname" . }}
        - secretRef:
          name: {{ include "studyon.db.fullname" . }}
      ports:
        - name: http
          containerPort: {{ .Values.django.containerPort }}
          protocol: TCP
      command: ["celery", "-A", "config", "beat", "-l", "info"]