apiVersion: v1
kind: Service
metadata:
  name: {{ include "studyon.celery.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "studyon.celery.labels" . | nindent 4 }}
spec:
  type: {{ .Values.flowerService.type }}
  ports:
    - port: {{ .Values.flowerService.port }}
      targetPort: {{ .Values.flower.containerPort }}
      protocol: TCP
  selector:
    {{- include "studyon.celery.selectorLabels" . | nindent 4 }}